- README.md
This repo didn't show up for "homebrew update in the background", adding 'background' to the README should help with that.
> Tweak Readme for SEO

- lib/autoupdate/start.rb
On default, when installation from bottle fails, homebrew would fall back to build from source.
But due to autoupdate happens at background, we cannot notice this in time and may often lead to unwanted battery drain.
I added an environment variable in the update script to prevent this, and this method is found [here](https://discourse.brew.sh/t/solved-option-to-not-build-from-source/3858)
> Disable building from source on failure

- lib/autoupdate/status.rb
The "not installed" language is a bit misleading. I recently reconfigured my computer using my personal bootstrap repo which installs autoupdate, but never runs `brew autoupdate --start`. Thus, when I tried running `brew autoupdate --status`, I thought something had gone wrong with the installation (unlikely since I used a Brewfile). The previous message looks like it could be `brew` itself saying the command is not installed.
After trying `brew autoupdate --version` I realized what had happened. Since this message can only ever be displayed once the package is installed, using the term "configured" makes more sense, at least to me.
> Clarify language in `--status` when no plist found

- lib/autoupdate/start.rb
Since auto-updating is usually not critical its daemon should play nice and try to lower its resource use when there are other higher priority task running.
> Added keys to plist to lower os priority

- lib/autoupdate/start.rb
RunAtLoad is not recommended in the launchd.plist manpage:
> This key should be avoided, as speculative job launches
> have an adverse effect on system-boot and user-login scenarios.
See https://github.com/DomT4/homebrew-autoupdate/issues/28#issue-671491340 for more details.
> Remove RunAtLoad key

- .github/workflows/tests.yml
- README.md
- cmd/autoupdate.rb
- lib/autoupdate/stop.rb
Required for https://github.com/Homebrew/brew/pull/11137
While we're here, add a CI job to ensure that `brew style` doesn't fail in future.
> Fix `brew style` and `vale` failures.

- README.md
This PR updates some URLs in the README and also makes some minor style changes:
* "Related Issue" URLs have been updated to use `Homebrew/homebrew-autoupdate`.
* The abbreviation of "versus" is generally lowercased `v`, `vs`, `v.` or `vs.`, so a section header has been updated.
* The same section header has been modified to use code syntax for `brew`.
* The sentence "Homebrew themselves..." has been modified to "Homebrew slightly frowns upon...", this is an official Homebrew tap after all!
Please don't feel pressured to accept any suggestion you aren't comfortable with. Thanks!
> README: update URLs

- lib/autoupdate.rb
- lib/autoupdate/core.rb
- lib/autoupdate/notify.rb
- lib/autoupdate/version.rb
* Adds a `tap_dir` helper to `core`, unifying the code in `notify` and `version`.
* Uses that new helper in the aforementioned files to streamline the code.
* Unifies some `requires`, and alphabetises the require-all `autoupdate.rb` file.
> core: add tap_dir helper; use it

- lib/autoupdate/status.rb
Since we don't roll out features forcefully, generally requiring users to delete/restart the command _(for example to move from `terminal-notifier` to our new AppleScript applet notifier on Catalina/Big Sur)_, let's start telling users when `autoupdate` has been running for a particularly lengthy period and nudging them to restart the command.
90 days is my initial range but as this tap reaches a more feature-complete stage that number can/will be increased beyond 3 months.
> status: determine days old; warn user if not restarted periodically

- README.md
- cmd/autoupdate.rb
- lib/autoupdate/start.rb
Starting immediately is useful for both debugging and for various use-cases beyond that, so let's support it formally rather than hiding it behind the `--debug` flag.
> autoupdate: add `--immediate` flag for `start`

- lib/autoupdate/version.rb
Changes since last version:
1be3b4c version: bump to 2.15.0
cfeb480 README: update help text
0f5b9e2 start: add full support for running immediately
1e5fd25 autoupdate: add --immediate switch to `start`.
6042eb9 autoupdate: minor description changes
df59fef status: determine days old; warn user if not restarted periodically
8dd3ee2 notify: remove redundant requires
55dd445 notify: use core tap_dir helper
d70752c version: use core tap_dir helper
901cabc core: add tap_dir helper
26e4244 autoupdate: alphabetise; require tap/formula
7dcedb8 version: add autogenerated release notes
> version: bump to 2.15.0

- lib/autoupdate/start.rb
My half-assed attempt at trying to fix the annoying macOS quarantine "[The app can’t be opened because it is from an unidentified developer](https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/faq/app_cant_be_opened.md)" error.
Respecting the `HOMEBREW_CASK_OPTS` env var, just like some other env vars are already respected.
As discussed in https://github.com/Homebrew/homebrew-autoupdate/issues/66#issuecomment-890227342. Based on the information from https://github.com/Homebrew/homebrew-cask/blob/HEAD/USAGE.md#options.
```sh
HOMEBREW_CASK_OPTS="--no-quarantine" brew autoupdate start 43200 --upgrade
```
Even when going with an alternative approach, I think respecting `HOMEBREW_CASK_OPTS` is worthwile either way.
- Statically or conditionally pass `--no-quarantine` as part of:
- …
> feat(start): respect `HOMEBREW_CASK_OPTS` env

- README.md
- cmd/autoupdate.rb
- lib/autoupdate/start.rb
`--greedy` cask upgrade is now opt-in instead of mandatory.
Fixes #58
I'm not sure how to properly test this. This is what I did
1. Switch to my branch in the system's brew tap
```console
$ cd "$(brew --repository homebrew/homebrew-autoupdate)"
$ git remote add erikw git@github.com:erikw/homebrew-autoupdate.git
$ git fetch erikw
$ git checkout opt-in-greedy
```
1. In `lib/autoupdate/start.rb` I added a little argument logger [here](https://github.com/Homebrew/homebrew-autoupdate/blob/dfb2bdc5798ece8f842847369054e9833c7aef93/lib/autoupdate/start.rb#L77) of what will be executed:
```ruby
File.open("/tmp/start.rb.log", "a") do |f|
f.write auto_args
end
```
1. Enable the autoupdate with and without the `--greedy`
```console
$ brew autoupdate start 5 --upgrade
$ brew autoupdate stop
$ brew …
```
> Add --greedy argument

- lib/autoupdate/start.rb
- lib/autoupdate/version.rb
* Warn of `terminal-notifier` deprecation coming.
* Bump `version` to reflect changes, and generate new automatic changelog for recent fixes/amendments/etc.
> various: updates

- cmd/autoupdate.rb
- I noticed a missing space in https://github.com/Homebrew/brew/pull/12962. Plus I was confused there as to why we tell people to look at `brew(1)` when these docs appear there too. Instead, let's give a brief in-line description of what `--greedy` does for casks.
> autoupdate: Fix `greedy` docs

- README.md
- cmd/autoupdate.rb
- lib/autoupdate/start.rb
If you want to start the autoupdate immediately and after every reboot, pass `--immediate`.
> Updated description of --immediate to include that it will also run after every reboot instead of waiting for 1 interval to pass

- README.md
- cmd/autoupdate.rb
- gui/getpass.sh
- lib/autoupdate/start.rb
Solves Issue https://github.com/Homebrew/homebrew-autoupdate/issues/40
You can now pass the argument `--sudo` to the `start` command.
If a Cask requires sudo, pinetry-mac will open a gui to ask for the password:
> password gui with pinentry-mac for handling Casks that require sudo

- cmd/autoupdate.rb
Adds a missing space to the `--sudo` switch description text. This is blocking manpage updates in Homebrew/brew. See https://github.com/Homebrew/brew/pull/16208
> Add missing space to `--sudo` switch description

- lib/autoupdate/start.rb
I noticed that even when you do not pass `--sudo` to the `start` command, the file `brew_autoupdate_sudo_gui` was still created.
It was empty but still unnecessary.
> Only create brew_autoupdate_sudo_gui script if --sudo is passed

- README.md
Follow-up for PR: https://github.com/Homebrew/homebrew-autoupdate/pull/114
* Removed embedded `--help` command output and inserted a link to the auto updated documentation: [Homebrew Documentation autoupdate subcommand](https://docs.brew.sh/Manpage#autoupdate-subcommand-interval-options)
* Added an example and recommended `start` command.
* Fixed some small spelling mistakes
> Updated README.md file (removed embedded --help command output + fixed small spelling mistakes)

- lib/autoupdate/start.rb
- Adds a timeout to `pinentry-mac`. This way, if Homebrew Autoupdate attempts an upgrade with `--sudo` when the user is not available to enter the admin password, the upgrade of that cask can fail and any remaining upgrades can proceed.
- Eliminates the need to store the admin password in a variable and then print that var to stdout. `sudo --askpass` expects the helper program to output to stdout. pinentry already prints to stdout. That's processed with awk and also printed to stdout already. Addresses my [comment](https://github.com/Homebrew/homebrew-autoupdate/issues/40#issuecomment-1806958098) in issue #40.
- While there, limit the scope of `PATH`. We already require the formula pinentry-mac, which is linked to `HOMEBREW_PREFIX/bin`. So, set that as PATH and use a full path for …
> sudo_gui_script_contents: add timeout, remove unnecessaries

- .github/dependabot.yml
- .github/workflows/generate-help-output.yml
Motivation: CI tests failure about `actions/setup-python@v4` being too old to run on GitHub Actions.
Ref https://github.com/DomT4/homebrew-autoupdate/actions/runs/12152862012/job/33889987720?pr=152
> ci: bump `actions/setup-python` to v5 and add dependabot

- lib/autoupdate/start.rb
Closes https://github.com/DomT4/homebrew-autoupdate/issues/145. Ref https://github.com/GPGTools/pinentry/blob/master/doc/pinentry.texi#L483
> start: enable pinentry passphrase caching

- .github/workflows/generate-help-output.yml
- .github/workflows/stale-issues.yml
- sync `triage-issues.yml` from upstream Homebrew/.github repo (renamed to `stale-issues.yml` in [Commit a85ce1d](https://github.com/Homebrew/.github/commit/a85ce1d1e59f0e1364448b76aa1c0c7e042043ed#diff-0bd376ac0f6d23a1457b2e910fd30cdd4cda10374ce15faa09c6ad26c3b82abe "https://github.com/Homebrew/.github/commit/a85ce1d1e59f0e1364448b76aa1c0c7e042043ed#diff-0bd376ac0f6d23a1457b2e910fd30cdd4cda10374ce15faa09c6ad26c3b82abe"))
- update repo owner in `stale-issues.yml`:
In `stale-issues.yml` (formerly `triage-issues.yml`), there is a condition which makes it run only when the repository owner is `Homebrew`. This means the workflow hasn't actually run for the past [11 months](https://github.com/DomT4/homebrew-autoupdate/actions/workflows/triage-issues.yml?page=16 …
> ci: sync stale issues workflow and pin actions to full commit SHA

- cmd/autoupdate.rb
Now complies with AbstractCommand.
See https://docs.brew.sh/External-Commands.
Closes GH-147
@DomT4
> refactor: Replace deprecated behaviour

- README.md
- cmd/autoupdate.rb
- lib/autoupdate/start.rb
- lib/autoupdate/version.rb
9948318 version: bump to 3.2.1
a42a282 autoupdate: allow 2 args to fix regression
01613d5 start: remove deprecation warning
d839fff autoupdate: remove outdated flag
> version: bump to 3.2.1

- README.md
- cmd/autoupdate.rb
- lib/autoupdate/start.rb
This PR adds a new option `--leaves-only` that only upgrades formulae that are not dependencies of another installed formula (top-level packages). This provides a safer upgrade strategy by reducing the risk of compatibility issues from dependency updates.
The option works by using the output of `brew leaves` to determine which packages to upgrade, rather than upgrading all installed packages.
> Add --leaves-only option for safer upgrades

- lib/autoupdate/status.rb
Setting up autoupdate this morning, I was initially confused when the status message told me the launch daemon was created two months ago! Then I realised that the date uses the US `mm/dd/yyyy` format (which [few other countries use](https://en.wikipedia.org/wiki/List_of_date_formats_by_country#Usage_map)).
I'm so used to tools using regional settings when formatting dates, that this really took me by surprise! I did some digging to work out why the date wasn't being formatted with regional settings, only to find that Ruby doesn't do this automatically (at least not without a lot of [extra work!](https://softwarepatternslexicon.com/patterns-ruby/24/15/)).
So instead, I'm proposing a simple switch of format, from `%D` to `%v` because the 'VMS' format is unambiguous: `dd-MMM-yyyy`.
I've …
> Use an unambiguous date format in status.rb
